### PR TITLE
0.21 - Long Polling support

### LINKED ISSUE #64: Add support for long polling
0.21.0 looks set to support long polling in the client. See: https://github.com/zeebe-io/zeebe/pull/2930

### PR DESCRIPTION
**Pull request by jwulf**
Fixes #64. 

## Long Polling

* Adds Long Polling support for 0.21.
* Off by default.
* Hardcoded to 10-minute polling cycle for ease to make configuration simple.
* Documented in the README.

## Test Refactoring

* Tests failed intermittently. Jest runs them in random order, some orders fail due to shared state.
* Added distinct processes for distinct tests. Use distinct task types in those processes.
* Cancel workflow instances after tests.
* Move tests into distinct files to promote modularity. (Ability to run individually, map test file to bpmn process)

### CODE REVIEW

**Comment by jwulf** [comment]
Don't merge this yet, long polling works with the SNAPSHOT release of Zeebe, but not with 0.21-alpha1; but other tests fail with the SNAPSHOT.

We have to wait for a stable release of 0.21 to test against.

**Comment by jwulf** [comment]
Zeebe e-commerce demo with inventory worker using long polling:

## With Simple Monitor enabled

Long poll:
```
Execution time (hr): 62s 662.513835ms
Execution time (hr): 54s 322.733574ms
Execution time (hr): 56s 696.164087ms
```
With 100ms continuous poll:

```
Execution time (hr): 53s 426.178514ms
Execution time (hr): 58s 519.939317ms
Execution time (hr): 90s 257.462871ms
```

The last one is probably due to the high volume of Activate Requests being processed by the exporter. There was another run before that one, but it had failed workflow creations, because the server load was too high. That one was 84s.

## With Broker Only

Long poll:

```
Execution time (hr): 42s 168.803361ms
Execution time (hr): 42s 173.879616ms
Execution time (hr): 42s 288.298501ms
```

With 100ms continuous poll:

```
Execution time (hr): 42s 328.696198ms
Execution time (hr): 42s 249.656159ms
Execution time (hr): 42s 252.437925ms
```

Conclusion: the client performance is the same, but long polling significantly reduces the load on the server.

**Comment by s3than** [comment]
Great addition to the test coverage.

**Comment by jwulf** [comment]
Superseded by #68

**Pull request closed without merging**
