### PR TITLE
0.19+TLS

### PR DESCRIPTION
**Pull request by jwulf**
This is a combination of Colin's TLS patch and the changes for 0.19.

### CODE REVIEW

**Comment by jwulf** [comment]
The tests pass locally against the Zeebe dev branch. We'll need to wait for a new Docker container build to get it to pass in CI.

**Comment by BrighTide** [comment]
👍 sweet

**Comment by s3than** [comment]
How long till we can get a new CI build?

**Comment by jwulf** [comment]
We have one now.

**Pull request merged**
